project:
  type: website
  output-dir: docs

website:
  favicon: assets/favicon.png
  page-navigation: true
  title: "Zachary T. Rewolinski"
  open-graph:
    # hopefully one of these changes the name above the url in google search
    site-name: "Zachary Rewolinski's Personal Website"
    title: "Zachary T. Rewolinski's Personal Website"
    # description:
  navbar:
    background: "#006994"
    search: true
    right:
      - text: "Publications"
        href: publications/index.qmd

      - text: "Teaching"
        href: teaching/index.qmd

      - text: "Blog"
        href: blog/index.qmd
        
      - text: "CV"
        href: cv.pdf

  page-footer:
    left: "&copy; Copyright 2024, Zachary Rewolinski"
    
# thought this would change the name of the website above the URL in google
# search, but it doesn't work.
# title: "Zachary T. Rewolinski's Personal Website"
    
format:
  html:
    theme: cosmo
    css: styles.css
    # toc: true # uncomment to allow table of contents on each page


