project:
  type: website
  output-dir: docs

website:
  favicon: assets/favicon.png
  page-navigation: true
  title: "Zachary T. Rewolinski"
  navbar:
    background: "#006994"
    search: true
    right:
      - text: "Publications"
        href: publications/index.qmd

      - text: "Teaching"
        href: teaching/index.qmd

      - text: "Blog"
        href: blog/index.qmd
        
      - text: "CV"
        href: cv.pdf

  page-footer:
    left: "&copy; Copyright 2024, Zachary Rewolinski"
    
format:
  html:
    theme: cosmo
    css: styles.css
    # toc: true # uncomment to allow table of contents on each page


