---
title: "Research"
---

*Note that \* denotes equal contribution.*

## Preprints

[Sanity Checks for Agentic Data Science](https://arxiv.org/pdf/2604.11003)<br>
**Z. T. Rewolinski**\*, A. V. Zane\*, H. Huang, C.Singh, C. Wang, J. Gao, B. Yu<br>
Under Review, 2026+

## Publications

[Predictability–Computability–Stability Workflow for Veridical Data Science in the Age of Artificial Intelligence](https://royalsocietypublishing.org/rsta/article/384/2321/20240605/481951/Predictability-Computability-Stability-workflow)<br>
**Z. T. Rewolinski**, B. Yu<br>
Philosophical Transactions of the Royal Society A: Mathematical, Physical and Engineering Sciences, 2026

[Local MDI+: Local Feature Importances for Tree-Based Models](https://arxiv.org/abs/2506.08928)<br>
Z. Liang\*, **Z. T. Rewolinski**\*, A. Agarwal, T. Tang, B. Yu<br>
Transactions on Machine Learning Research (TMLR), 2026

[A Low-Rank Tensor Completion Approach for Imputing Functional Neuronal Data from Multiple Recordings](https://ieeexplore.ieee.org/abstract/document/9820079)<br>
L. Zheng, **Z. T. Rewolinski**, G. I. Allen<br>
IEEE Data Science and Learning Workshop (DSLW), 2022

## Presentations

[COVID-19 Policy Impacts on NO2, Ozone, and PM2.5 Levels in U.S. Cities](https://ams.confex.com/ams/101ANNUAL/prelim.cgi/Paper/385119)<br>
Y. Choi, H. Louh, D. Cohan, D. Kowal, **Z. T. Rewolinski**, A. Nguyen, J. Li, A. Dayan, A. Abbott<br>
American Meteorological Society (AMS) Annual Meeting, Poster Presentation, 2021

[Responses of human activity & in-situ & satellite-observed air quality in U.S. cities to the COVID pandemic](https://ui.adsabs.harvard.edu/abs/2020AGUFMA070...08C/abstract)<br>
D. Cohan, D. Kowal, Y. Choi, J. Li, H. Louh, R. MacDonald, G. Meriano, A. Nguyen, L. Niu, **Z. T. Rewolinski**<br>
American Geophysical Union (AGU) Fall Meeting, Oral Presentation, 2020

[COVID-19 Policy Impacts on NO2, Ozone, and PM2.5 Levels in U.S. Cities](https://ui.adsabs.harvard.edu/abs/2020AGUFMA067.0007L/abstract)<br>
H. Louh, Y. Choi, J. Li, A. Nguyen, **Z. T. Rewolinski**, D. Kowal, D. Cohan<br>
American Geophysical Union (AGU) Fall Meeting, Poster Presentation, 2020

[Impacts of COVID-19 Pandemic on Activity and Emissions](https://www.cmascenter.org/conference/2020/session-presentations2.cfm)<br>
**Z. T. Rewolinski**, J. Li, A. Nguyen, D. Cohan, D. Kowal<br>
Community Modeling and Analysis Systems (CMAS) Conference, Oral Presentation, 2020

[An Analysis of the Relationship Between Pitcher Size and UCL Tears](https://sabr.org/convention/2019/posters)<br>
**Z. T. Rewolinski**<br>
Society for American Baseball Research (SABR) National Convention, Poster Presentation, 2019<br>
- *Best Poster Award*
