---
title: "Teaching"
---

## UC Berkeley

| Role                        | Number   | Title                                                             | Semester(s)              | Description                                                              |
|-----------------------------|----------|-------------------------------------------------------------------|--------------------------|--------------------------------------------------------------------------|
| Graduate Student Instructor | STAT 214 | Data Analysis and Machine Learning for Real-World Decision Making | Spring 2025, Spring 2026 | Masters course on data science and machine learning.                     |
| Graduate Student Instructor | STAT 133 | Concepts in Computing with Data                                   | Spring 2024              | Upper-level course on computationally intensive applied statistics in R. |

## Rice University

| Role               | Number       | Title                              | Semester(s)                         | Description                                                                           |
|--------------------|--------------|------------------------------------|-------------------------------------|---------------------------------------------------------------------------------------|
| Teaching Assistant | DSCI 101     | Introduction to Data Science       | Spring 2023                         | Introductory-level course on the fundamentals of data science and Python programming. |
| Grader             | STAT 411     | Advanced Statistical Methods       | Spring 2023                         | Upper-level course on advanced topics in statistical applications.                    |
| Teaching Assistant | ELEC 478/578 | Introduction to Machine Learning   | Fall 2022                           | Graduate-level course on machine learning.                                            |
| Grader             | STAT 425     | Introduction to Bayesian Inference | Fall 2022                           | Upper-level course introducing Bayesian statistics.                                   |
| Teaching Assistant | COMP 140     | Computational Thinking             | Fall 2020, Spring 2021, Spring 2022 | Introductory-level computer science course.                                           |
